### ISSUE TITLE
Can't run test from OpenEdge 11.5

### ISSUE THREAD

**Issue by LievenDeFoor** [CameronWills/OEUnit#15]
When trying to run a test from OpenEdge 11.5 Developer Studio you get the following error:

Encountered an input-blocking statement while executing a user-defined function or non-void method: 'propGet_ResultsWindow' that is invalid within the current runtime context. (2780)

Running the same from 11.3 works without problems...

**Comment by mvbergeijk** [comment]
The error is caused by statement "RUN getViewHwnd IN hOEIDEService 
      (viewId, viewTitle, OUTPUT viewHwnd) NO-ERROR.".
For some reason it invokes _wait.p and executes a wait-for.

**Comment by LievenDeFoor** [comment]
Guess this one can be closed now...
